
package com.liyf.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WeatherServiceService", targetNamespace = "http://webservice.liyf.com/", wsdlLocation = "http://localhost:8080/ws_server/weather?wsdl")
public class WeatherServiceService
    extends Service
{

    private final static URL WEATHERSERVICESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ws_server/weather?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WEATHERSERVICESERVICE_WSDL_LOCATION = url;
    }

    public WeatherServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherServiceService() {
        super(WEATHERSERVICESERVICE_WSDL_LOCATION, new QName("http://webservice.liyf.com/", "WeatherServiceService"));
    }

    /**
     * 
     * @return
     *     returns WeatherService
     */
    @WebEndpoint(name = "WeatherServicePort")
    public WeatherService getWeatherServicePort() {
        return (WeatherService)super.getPort(new QName("http://webservice.liyf.com/", "WeatherServicePort"), WeatherService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherService
     */
    @WebEndpoint(name = "WeatherServicePort")
    public WeatherService getWeatherServicePort(WebServiceFeature... features) {
        return (WeatherService)super.getPort(new QName("http://webservice.liyf.com/", "WeatherServicePort"), WeatherService.class, features);
    }

}
